[package]
name = "rustjourneyplanner"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1

[dependencies]
anyhow = "1.0.75"
leptos = { version = "0.5.2", features = ["csr", "nightly"] }
petgraph = "0.6.4"
reqwest = "0.11.22"
serde_json = "1.0.108"
