[package]
name = "eve_sde_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
eve_sde = { path = "../eve_sde" }
serde = { version ="1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_yaml = "0.9.27"
zip = "0.6.6"
